### ISSUE TITLE
CUDA 12.3 support

### ISSUE THREAD

**Issue by t-linguist** [jllllll/bitsandbytes-windows-webui#21]
```
PS C:\Users\alice> python -m bitsandbytes
bin B:\Programs\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++++ PYTORCH CUDA PATHS ++++++++++++++++++++
B:\Programs\Lib\site-packages\torch\lib\c10_cuda.dll
B:\Programs\Lib\site-packages\torch\lib\cudart64_12.dll
B:\Programs\Lib\site-packages\torch\lib\torch_cuda.dll

+++++++++++++++++++ CUDA_PATH CUDA PATHS +++++++++++++++++++
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\cudart64_12.dll
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\extras\visual_studio_integration\MSBuildExtensions\Nvda.Build.CudaTasks.v12.3.dll

Error occurred while executing command: where /R "C:\Users\alice" "*cuda*dll"
Error message: €Ќ”ЋђЊЂ–€џ: ­Ґ г¤ Ґвбп ­ ©вЁ д ©«л Ї® § ¤ ­­л¬ и Ў«®­ ¬.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "B:\Programs\Lib\site-packages\bitsandbytes\__main__.py", line 132, in <module>
    generate_bug_report_information()
  File "B:\Programs\Lib\site-packages\bitsandbytes\__main__.py", line 96, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*' + SHARED_LIB_EXTENSION)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\Programs\Lib\site-packages\bitsandbytes\__main__.py", line 53, in find_file_recursive
    raise RuntimeError('Something went wrong when trying to find file.')
RuntimeError: Something went wrong when trying to find file.
```
As far as I understand, the installation can't be completed since I have CUDA 12.3. Hope you will fix it soon :)

**Comment by jllllll** [comment]
I'm planning to when I have the time.

**Comment by SuperMasterBlasterLaser** [comment]
There is also CUDA 12.4 I hope you will add support

**Comment by MarsAdventure** [comment]
I hope you will add cuda 12.3 support
