### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 11: invalid start byte****

### ISSUE THREAD

**Issue by besn0847** [jllllll/bitsandbytes-windows-webui#25]
Hi,

I'm using CUDA 12.1 and installed [bitsandbytes-0.41.2.post2] but i get a UnicodeDecodeError when i run 'python -m bitsandbytes'.
Any idea what is going on ?

Below the error message

Cheers

bin E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda122_nocublaslt.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torch\lib\c10_cuda.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torch\lib\cudart64_12.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torch\lib\torch_cuda.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torchvision\cudart64_12.dll

++++++++++++++++++++ PYTORCH CUDA PATHS ++++++++++++++++++++
E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torch\lib\c10_cuda.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torch\lib\cudart64_12.dll

E:\Applications\Anaconda3\envs\base310\Lib\site-packages\torch\lib\torch_cuda.dll

+++++++++++++++++++ CUDA_PATH CUDA PATHS +++++++++++++++++++
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_12.dll

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\extras\visual_studio_integration\MSBuildExtensions\Nvda.Build.CudaTasks.v12.1.dll

Traceback (most recent call last):
  File "E:\Applications\Anaconda3\envs\base310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Applications\Anaconda3\envs\base310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 121, in <module>
    generate_bug_report_information()
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 85, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*' + SHARED_LIB_EXTENSION)
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 39, in find_file_recursive
    out, err = execute_and_return(cmd)
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 34, in execute_and_return
    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 26, in execute_and_return_decoded_std_streams
    return _decode(
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 20, in _decode
    return tuple(
  File "E:\Applications\Anaconda3\envs\base310\lib\site-packages\bitsandbytes\__main__.py", line 21, in <genexpr>
    to_decode.decode("UTF-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 11: invalid start byte****

**Comment by axel578** [comment]
Same here !'utf-8' codec can't decode

**Comment by axel578** [comment]
I modified bitsandbytes site packcakge code with try and except, except it return ('','') for the function with _decode, and it seams to be okay, just not, the command failing is :
where /R "C:\Users\myuser\Desktop\AI\3D\mypythonproject" "*cuda*dll"

Why is it looking for cuda dll in my python folder ????? of course it won't find anything, note, this folder is nowhere in environment variable
