### ISSUE TITLE
UnboundLocalError: local variable 'conda_cuda_libs' referenced before assignment on bitsandbytes 0.40.1post1

### ISSUE THREAD

**Issue by Panchovix** [jllllll/bitsandbytes-windows-webui#9]
Hi there, nice work as always!

Have started to get this issue after updating bistandbytes to 0.40.1post1 version.

The complete error is

```
Traceback (most recent call last):
  File "I:\merge model\mergemodel.py", line 5, in <module>
    from peft import PeftModel
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\peft\peft_model.py", line 34, in <module>
    from .tuners import (
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\peft\tuners\lora.py", line 41, in <module>
    import bitsandbytes as bnb
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 126, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 440, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "F:\ChatIAs\oobabooga\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 315, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(conda_cuda_libs)
UnboundLocalError: local variable 'conda_cuda_libs' referenced before assignment
```

The error goes away if using bitsandbytes 0.40.0post4

**Comment by jllllll** [comment]
I'm going through the code now. 0.40.1 build will be fixed and uploaded soon, then I will update to 0.40.2.

**Comment by jllllll** [comment]
I have uploaded a hopefully fixed build:
https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.40.1.post1-py3-none-win_amd64.whl

Please let me know if it works. Just started the 0.40.2 build, which should complete in around 30 minutes.

**Comment by Panchovix** [comment]
> I have uploaded a hopefully fixed build: https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.40.1.post1-py3-none-win_amd64.whl
> 
> Please let me know if it works. ~Just started the 0.40.2 build, which should complete in around 30 minutes.~ 0.40.2 build is now uploaded as well.

Just tested and it worked without issues, thanks!
